### ISSUE TITLE
Expect Applied not working

### ISSUE THREAD

**Issue by inonkp** [Brain-WP/BrainMonkey#50] opened 2019-07-12 08:57 UTC
Running the following:
        \Brain\Monkey\Filters\expectApplied('some_filter')->once()->with('arg1', 1);
        apply_filters('some_filter','arg1',1)
Yields:
Mockery\Exception\InvalidCountException: Method apply_filters_some_filter('arg1', 1) from Mockery_1 should be called
 exactly 1 times but called 0 times.

C:\Users\qwerty\AppData\Local\Temp\wordpress-tests-lib\vendor\mockery\mockery\library\Mockery\CountValidator\Exact.php:38
C:\Users\qwerty\AppData\Local\Temp\wordpress-tests-lib\vendor\mockery\mockery\library\Mockery\Expectation.php:310
C:\Users\qwerty\AppData\Local\Temp\wordpress-tests-lib\vendor\mockery\mockery\library\Mockery\ExpectationDirector.php:119
C:\Users\qwerty\AppData\Local\Temp\wordpress-tests-lib\vendor\mockery\mockery\library\Mockery\Container.php:303
C:\Users\qwerty\AppData\Local\Temp\wordpress-tests-lib\vendor\mockery\mockery\library\Mockery\Container.php:288
C:\Users\qwerty\AppData\Local\Temp\wordpress-tests-lib\vendor\mockery\mockery\library\Mockery.php:204
C:\Users\qwerty\AppData\Local\Temp\wordpress-tests-lib\vendor\brain\monkey\inc\api.php:38
C:\xampp72\htdocs\mca\wp-content\plugins\etsy_woocommerce\tests\EtsyProductTest.php:29

My setup:
phpunit 7.5.11
php 7.2.18

**Comment by widoz** [comment] 2019-07-13 22:55
@inonkp just to be sure did you setup it https://brain-wp.github.io/BrainMonkey/docs/wordpress-setup.html ?

**Comment by inonkp** [comment] 2019-07-14 03:50
This is my setup:

public function setUp(): void  {
        \Brain\Monkey\setUp();

        

        $this->mock = \Mockery::mock("SomeOtherClass")->makePartial()->shouldAllowMockingProtectedMethods();
        $this->mock->mock_init();
        $this->utils = $this->mock->mock_get_utils();
        parent::setUp();

    }
    
    public function tearDown(): void {
        parent::tearDown();
        \Brain\Monkey\tearDown();
    }

**Comment by gmazzap** [comment] 2019-07-15 06:46
Hi @inonkp 

I tried to reproduce your issue using your exact same version of PHP and PHPUnit.

I wanted to also use your setup, but `this->mock->mock_init()` and `$this->mock->mock_get_utils()` look like custom methods of your `SomeOtherClass` so I could not use those.

Moreover, normally you should probably call `parent::setUp();` before anything else.

This is the setup I used (literal copy & paste):

```php
class TestCase extends \PHPUnit\Framework\TestCase
{
    use \Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration;

    private $mock;
    private $utils;

    public function setUp(): void
    {
        parent::setUp();
        Brain\Monkey\setUp();

        $this->mock = \Mockery::mock("SomeOtherClass")
            ->makePartial()
            ->shouldAllowMockingProtectedMethods();
    }

    public function tearDown(): void
    {
        parent::tearDown();
        \Brain\Monkey\tearDown();
    }
}
```

And this is the test code I used (again c&p):

```php
class MyTest extends TestCase {

    public function testIssue50()
    {
        Brain\Monkey\Filters\expectApplied('some_filter')->once()->with('arg1', 1);

        apply_filters('some_filter', 'arg1', 1);
    }
}
```

When I run the test I get:

```
Time: 240 ms, Memory: 8.00 MB

OK (1 test, 1 assertion)
```

So **I could not reproduce the issue**.

Can you please double check that what you pasted here is your exact code?
Can you also check that the custom methods used in your setup are not the cause of the issue?

**Comment by inonkp** [comment] 2019-07-15 06:55
Thanks for taking the time to answer my question. I will double check.

**Comment by inonkp** [comment] 2019-07-15 19:06
I have commented out all unrelevant code to the test. This is what im
running:

<?php

class SomeTest extends \PHPUnit\Framework\TestCase{
/**
     *
     * @var \Mockery\MockInterface
     */
    private $mock;
    use \Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration;

    private $utils;
public function setUp(): void  {
        parent::setUp();
        \Brain\Monkey\setUp();
        //$this->mock =
\Mockery::mock("MockEtsyProduct")->makePartial()->shouldAllowMockingProtectedMethods();
        //$this->mock->mock_init();
        //$this->utils = $this->mock->mock_get_utils();


    }

    public function tearDown(): void {
        parent::tearDown();
        \Brain\Monkey\tearDown();
    }

    public function test_dummy(){

\Brain\Monkey\Filters\expectApplied('some_filter')->once()->with('arg1', 1);

        apply_filters('some_filter', 'arg1', 1);
    }
}

The problem must be in my setup, composer-wise, and how I bootstrap
phphunit..

**Comment by gmazzap** [comment] 2019-07-17 10:46
In the zip file below:

[brain-monkey-issue-50.zip](https://github.com/Brain-WP/BrainMonkey/files/3401441/brain-monkey-issue-50.zip)

You can fin the test code I used.

Unzip, open a terminal to the folder in it and run `composer install`.

It will install dependencies and then _automatically_ run the test.

It works perfectly for me. If it does not for you, then it might be something on the machine, e.g. some global Composer plugin.

**Comment by inonkp** [comment] 2019-07-17 10:47
Thanks will try.

**Comment by inonkp** [comment] 2019-07-17 16:17
Works.
Do you think its because of the phpunit version? Probably not...
Please note im running wordpress plugin tests according to this tutorial:
https://make.wordpress.org/cli/handbook/plugin-unit-tests/
Im pretty sure the reason is somewhere there.

**Comment by gmazzap** [comment] 2019-07-22 07:04
@inonkp I used the exact same PHPUnit version that you mentioned in your first comment,7.5.11

 I think the problem is the WordPress plugin unit tests.

Brain Monkey is designed to run tests _without_ WordPress. If you follow the tutorial you linked, you will run tests _with_ WordPress.

The two ways are not meant to be used _together_.

You can run unit tests without WordPress, using Brain Monkey, and then run integration/system/e2e tests _with_ WordPress.

**Comment by inonkp** [comment] 2019-07-22 10:51
I understand, thanks for taking the time for me.

**Comment by gmazzap** [comment] 2019-07-22 17:02
No problem.

I'm closing this. @inonkp  Feel free to re-open in case you need more info on this.

**Closed by gmazzap** 2019-07-22 17:02 UTC
